version: '3.8'
services:

  db:
    image: "mysql:8.0.30"
    restart: 'always'
    env_file:
      - "./.env"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_HOST_PORT:3306
    volumes:
      - db-data:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "$MYSQL_USER",
          "-p$MYSQL_PASSWORD"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: "./node-attendance-system-api"
    env_file:
      - "./.env"
    environment:
      - APP_PORT=$API_PORT
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $API_PORT:$API_PORT
    stdin_open: true
    tty: true

volumes:
  db-data:
